version: '3.9'
services:
  products:
    build: ./products
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      DB_CONNECTION_STRING: mysql://shoaib:Shoaib123@mysql:3306/products
      SERVICE_BUS_CONNECTION_STRING: Endpoint=sb://hadiya.servicebus.windows.net/;SharedAccessKeyName=sendlisten;SharedAccessKey=k5YwVx03r1ofjQL95U0Bd8FwNkkROyLS+ryfLjRVtG0=;EntityPath=product_cart
      SERVICE_BUS_QUEUE_NAME: product_cart
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on: [ mysql, elasticsearch ]
    networks:
      - hadiya_net
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Administrator123
      MYSQL_DATABASE: products
      MYSQL_USER: shoaib
      MYSQL_PASSWORD: Shoaib123
    volumes:
      - 'mysql_data:/var/lib/mysql'
    networks:
      - hadiya_net
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:8
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'hadiya_elasticsearch_data:/bitnami/elasticsearch/data'
    networks:
      - hadiya_net
  kibana:
    image: docker.io/bitnami/kibana:8
    ports:
      - '5601:5601'
    volumes:
      - 'hadiya_kibana_data:/bitnami/kibana'
    depends_on:
      - elasticsearch
    networks:
      - hadiya_net
  postgresql:
    image: docker.io/bitnami/postgresql:13
    volumes:
      - 'hadiya_sonar_postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_sonarqube
      - POSTGRESQL_DATABASE=bitnami_sonarqube
    networks:
      - hadiya_net
  sonarqube:
    image: docker.io/bitnami/sonarqube:9
    ports:
      - '80:9000'
    volumes:
      - 'hadiya_sonarqube_data:/bitnami/sonarqube'
    depends_on:
      - postgresql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_DATABASE_HOST=postgresql
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
    networks:
      - hadiya_net
  prometheus:
    image: bitnami/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - 'hadiya_prometheus_data:/opt/bitnami/prometheus/data'
      - './prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml'
    networks:
      - hadiya_net
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    networks:
      - hadiya_net

volumes:
  mysql_data:
    driver: local
  hadiya_elasticsearch_data:
    driver: local
  hadiya_kibana_data:
    driver: local
  hadiya_sonar_postgresql_data:
    driver: local
  hadiya_sonarqube_data:
    driver: local
  hadiya_prometheus_data:
    driver: local
networks:
  hadiya_net:
    driver: bridge