global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: products
    static_configs:
      - targets:
          - "http://products:3001/products/metrics"
        labels:
          project: hadiya
          app: products