global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: products
    metrics_path: /products/metrics
    static_configs:
      - targets:
          - "products:3001"
        labels:
          project: hadiya
          app: products